### ISSUE TITLE
issue with docker run command

### ISSUE THREAD

**Issue by benkeser** [Li1yxu/Final_Project_4#1]
You have an issue with your `docker run` command. Please review the [hints given on Canvas](https://canvas.emory.edu/courses/128222/discussion_topics/1034921)

**Comment by benkeser** [comment]
I'll grade when you close this issue

**Comment by Li1yxu** [comment]
Hi - I have made a change to the misplaced"/", please check how it goes!

**Comment by benkeser** [comment]
No, still issues. Please review more carefully. 

Also notice there is no report folder in the GitHub repo to catch the outputted report from the container. Do you need to add such a folder?

**Comment by Li1yxu** [comment]
I executed make final_project_image and
make final_report/obesity_report.html
it seems to be working? A final report folder will automatically generated in my local folder with the report in it.
I can add the report folder but i am still not sure which part has been the issue please hint me slightly!

**Comment by benkeser** [comment]
Copied from the canvas hints:

1. Make sure that in your Makefile, you are referencing the image that is on Dockerhub NOT an image that only exists locally.

So your command should be something like docker run <options> <your_dockerhub_name>/<your_image_tag>
Including your dockerhub name in the docker run call is important to automate the process of retrieving your image from docker hub and then running the container.

**Comment by Li1yxu** [comment]
OHH! -Thank you so much! That makes lots of sense, I have corrected the makefile.
